root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
include_ext = ["go", "templ"]
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_templ\\.go$"]
delay = 1000                                                    # ms

[log]
time = true

[screen]
clear_on_rebuild = true
